version: "3.9"

services:
  frontend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - backend-go
    restart: unless-stopped

  backend-go:
    build: ./backend-go
    restart: unless-stopped
